config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("hcare.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    path("bloodpressures/", include("hcare.bloodpressures.urls")),
    path("glucoses/", include("hcare.glucoses.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

hcare/bloodpressures/urls.py
from django.urls import path
from hcare.bloodpressures import views


app_name = "bloodpressures"
urlpatterns = [
    path("", views.BloodPressureListView.as_view(), name="list"),
    path("<int:pk>/", views.BloodPressureDetailView.as_view(), name="detail"),
    path("add/", views.BloodPressureCreateView.as_view(), name="add"),
    path("<int:pk>/update/", views.BloodPressureUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.BloodPressureDeleteView.as_view(), name='delete'),
]

hcare/glucoses/urls.py
from django.urls import path
from hcare.glucoses import views


app_name = "glucoses"
urlpatterns = [
    path("", views.GlucoseListView.as_view(), name="list"),
    path("<int:pk>/", views.GlucoseDetailView.as_view(), name="detail"),
    path("add/", views.GlucoseCreateView.as_view(), name="add"),
    path("<int:pk>/update/", views.GlucoseUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.GlucoseDeleteView.as_view(), name='delete'),
]

hcare/users/urls.py
from django.urls import path

from hcare.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

hcare/bloodpressures/models.py
from django.db import models
from django.urls import reverse


class BloodPressure(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='pressures')
    systolic = models.PositiveSmallIntegerField()
    diastolic = models.PositiveSmallIntegerField()
    pulse = models.PositiveSmallIntegerField()
    recorded = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'record {self.id}'

    def get_absolute_url(self):
        return reverse('bloodpressures:detail', kwargs={'pk': self.id})

hcare/glucoses/models.py
from django.db import models
from django.urls import reverse


class Glucose(models.Model):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='glucoses')
    glucose = models.PositiveSmallIntegerField()
    recorded = models.DateTimeField()
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'glucose record {self.id}'

    def get_absolute_url(self):
        return reverse('glucoses:detail', kwargs={'pk': self.id})

hcare/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

hcare/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

hcare/bloodpressures/views.py
# from django.shortcuts import render

from django.db.models import QuerySet
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from .models import BloodPressure


class BloodPressureListView(LoginRequiredMixin, ListView):
    model = BloodPressure

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(user=self.request.user)


class BloodPressureDetailView(LoginRequiredMixin, DetailView):
    model = BloodPressure

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(user=self.request.user)


class BloodPressureCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = BloodPressure
    fields = ['systolic', 'diastolic', 'pulse', 'notes']
    success_url = reverse_lazy('bloodpressures:list')
    success_message = 'Record created successfully.'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # form.fields['recorded'].widget = DateTimeInput(
        #     attrs={'type': 'datetime-local', 'class': 'form-control'}
        # )
        return form

    def form_valid(self, form):
        bloodpressure = form.save(commit=False)
        bloodpressure.user = self.request.user
        bloodpressure.save()
        return super().form_valid(form)


class BloodPressureUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = BloodPressure
    fields = ['systolic', 'diastolic', 'pulse', 'notes']
    template_name = 'bloodpressures/bloodpressure_update_form.html'  # nadpisany template
    success_url = reverse_lazy('bloodpressures:list')
    success_message = 'Record updated successfully.'


class BloodPressureDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = BloodPressure
    success_url = reverse_lazy('bloodpressures:list')

hcare/glucoses/views.py
from django.shortcuts import render

from django.db.models import QuerySet
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import DateTimeInput
from .models import Glucose


class GlucoseListView(LoginRequiredMixin, ListView):
    model = Glucose

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(user=self.request.user)


class GlucoseDetailView(LoginRequiredMixin, DetailView):
    model = Glucose

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(user=self.request.user)


class GlucoseCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Glucose
    fields = ['glucose', 'recorded', 'notes']
    # success_url = reverse_lazy('glucoses:list') # get url from model absolute url in template
    success_message = 'Record created successfully.'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['recorded'].widget = DateTimeInput(
            attrs={'type': 'datetime-local', 'class': 'form-control'}
        )
        return form

    def form_valid(self, form):
        glucose = form.save(commit=False)
        glucose.user = self.request.user
        glucose.save()
        return super().form_valid(form)


class GlucoseUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Glucose
    fields = ['glucose', 'recorded', 'notes']
    template_name = 'glucoses/glucose_update_form.html'  # nadpisany template
    success_url = reverse_lazy('glucoses:list')
    success_message = 'Record updated successfully.'


class GlucoseDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Glucose
    success_url = reverse_lazy('glucoses:list')

hcare/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

hcare/templates/bloodpressures/bloodpressure_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>{% blocktrans %}Do you want to permanently delete "{{ object }}" ?{% endblocktrans %}</p>
  {{ form }}
  <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
</form>
{% endblock %}

hcare/templates/bloodpressures/bloodpressure_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>{{ object.recorded }}</h1>
  <table class="table table-condensed align-left">
    <tr>
      <th>{% trans "Systolic pressure" %}</th>
      <td>{{ object.systolic }}</td></tr>
    <tr>
      <th>{% trans "Diastolic pressure" %}</th>
      <td>{{ object.diastolic }}</td></tr>
    <tr>
      <th>{% trans "Pulse" %}</th>
      <td>{{ object.pulse }}</td></tr>
    <tr>
      <th>{% trans "Notes" %}</th>
      <td>{{ object.notes }}</td></tr>
  </table>
  <br>
  <a href="{% url 'bloodpressures:update' object.id %}"
     class="btn btn-success">{% trans "Update" %}</a>
  <a href="{% url 'bloodpressures:delete' object.id %}"
     class="btn btn-danger">{% trans "Delete" %}</a>
  <br><br>
  <a href="{% url 'bloodpressures:list' %}" class="btn btn-outline-secondary">
    {% trans "Retrun to list" %}
  </a>
{% endblock %}

hcare/templates/bloodpressures/bloodpressure_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<h1>{% trans "Add pressure record" %}</h1>
<form method="post" action="{% url 'bloodpressures:add' %}">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
</form>
{% endblock %}

hcare/templates/bloodpressures/bloodpressure_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
  <table class="table table-stripped">
    <thead>
      <tr>
        <th scope="col">{% trans "Date" %}</th>
        <th scope="col">{% trans "Systolic pressure" %}</th>
        <th scope="col">{% trans "Diastolic pressure" %}</th>
        <th scope="col">{% trans "Pulse" %}</th>
      </tr>
    </thead>
      <tbody>
       {% for obj in object_list %}
        <tr>
          <td><a href="{{ obj.get_absolute_url }}">{{ obj.recorded }}</a></td>
          <td>{{ obj.systolic }}</td>
          <td>{{ obj.diastolic }}</td>
          <td>{{ obj.pulse }}</td>
        </tr>
       {% endfor %}
      </tbody>
  </table>
  <br>
  <a href="{% url 'bloodpressures:add' %}" class="btn btn-success">{% translate "Add" %}</a>
{% endblock %}

hcare/templates/bloodpressures/bloodpressure_update_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<h1>{% trans "Update" %}</h1>
<form method="post" action="{% url 'bloodpressures:update' object.id %}">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
</form>
{% endblock %}